# Session 4

Numpy also provides many functions to create arrays:

In [2]:
import numpy as np

In [3]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

[[0. 0.]
 [0. 0.]]


In [4]:
b = np.ones((3,2))   # Create an array of all ones
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [5]:
d = np.eye(4)        # Create a 2x2 identity matrix
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
c = np.full((3,2), 7) # Create a constant array
print(c)

[[7 7]
 [7 7]
 [7 7]]


In [13]:
e = np.random.random((3,2)) # Create an array filled with random values
print(e)

[[0.06948712 0.22465217]
 [0.05804382 0.70246125]
 [0.35326208 0.53956302]]


In [26]:
b = np.random.randint(low = 3,high = 15,size =(4,4))  # high is exclusive
b

array([[13, 11,  5, 13],
       [ 9, 10, 14, 12],
       [11, 10,  4, 12],
       [ 7, 12, 10, 11]])

Task


create  a ticket system chocess random between  141 fan

every time we choose 4 fans 

In [29]:
fans = np.random.randint(low = 1,high = 142,size =4)  # high is exclusive
fans

array([ 59, 133, 131,  81])

### Array indexing

Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [30]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [31]:
a.shape

(3, 4)

In [32]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
a[1,1:]

array([6, 7, 8])

In [34]:
a[ 1:  , 1:3 ]  # last is exclusive

array([[ 6,  7],
       [10, 11]])

In [35]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
a[ :2 , :-1 ]  

array([[1, 2, 3],
       [5, 6, 7]])

In [38]:
b = a[ 0:2,1:3]     # last is exclusive
print(b)

[[2 3]
 [6 7]]


You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array. Note that this is quite different from the way that MATLAB handles array slicing:

In [39]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [40]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])
print(a)



[[1 2]
 [3 4]
 [5 6]]


In [41]:
bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [43]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])

# We can do all of the above in a single concise statement:
print(a[a > 2])

[3 4 5 6]


In [44]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [45]:
a[a < 5] 

array([1, 2, 3, 4])

In [46]:
a[a < 1] 

array([], dtype=int32)

In [48]:
a[a < 1].shape[0]

0

Task 

1- create array 2D   shape 3 , 4    (random)

2- print > 5 using (Boolean indexing) 

3-  print row 2 col 3 

In [52]:
ar = np.random.randint(low=50,size=(3,4))

In [53]:
ar[ar>5]

array([49, 49, 42, 48, 16, 29, 34, 28, 37, 38])

For brevity we have left out a lot of details about numpy array indexing; if you want to know more you should read the documentation.

### Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [54]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

int32 float64 int64


Int16 can only store values up to 2^16 =  32,767  

Int32 can store values up to 2^31  =  2,147,483,647  

Int64 can store values up to 2^63   = 9,223,372,036,854,775,807    

You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

### Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [55]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [56]:
# Elementwise sum; both produce the array
# print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]


In [57]:
# Elementwise difference; both produce the array
# print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]


In [59]:
x

array([[1., 2.],
       [3., 4.]])

In [60]:
y

array([[5., 6.],
       [7., 8.]])

In [58]:
# Elementwise product; both produce the array
# print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]


In [61]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
# print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


Task 

1- create function takes two arrays >>>>  size of array (3,3)

2- print multiply two arrays

3- print subtract 2 arrays

4- return sub array size 2,2 from result of multiply


In [62]:
def oper(x1,x2):
    print('Multi')
    print(np.multiply(x1,x2))
    print('subtract')
    print(np.subtract(x1,x2))
    
    multi = np.multiply(x1,x2)
    
    return (multi[1:3,1:3])

arr1 = np.random.randint(low = 3,high = 15,size =(3,3))
arr2 = np.random.randint(low = 3,high = 15,size =(3,3))

result = oper(arr1,arr2) # call function

print(result)


Multi
[[ 24  81  48]
 [120  39  42]
 [ 65  56  20]]
subtract
[[  2   0  -2]
 [ -2 -10  -1]
 [  8  -1  -1]]
[[39 42]
 [56 20]]


In [63]:
x = np.array([[1 ,2],[3 , 4]])
x

array([[1, 2],
       [3, 4]])

In [64]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


Note that unlike MATLAB, `*` is elementwise multiplication, not matrix multiplication. We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [65]:
# x = np.array([[1,2],[3,4]])
# y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

print (v)
print(w)
# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

[ 9 10]
[11 12]
219
219


Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [67]:
x = np.array([[1,2],[3,4],[9,12]])
print(x)


[[ 1  2]
 [ 3  4]
 [ 9 12]]


In [68]:
print(np.sum(x))        # Compute sum of all elements; prints "10"


31


In [69]:
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"


[13 18]


In [70]:
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

[ 3  7 21]


task 

create an  array 4 rows 4 cols

make total sum for it

make total sum for every columns

In [71]:
x=np.arange(1,17).reshape(4,4)
print(x)
np.sum(x,axis = 0)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([28, 32, 36, 40])

You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [72]:
print(x)
print("transpose\n", x.T)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
transpose
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [73]:
v = np.array([[1,2,3]])
print( v )
print( "transpose\n", v.T)

[[1 2 3]]
transpose
 [[1]
 [2]
 [3]]


 2 3 6 1 2 5

 n= 6

 sum = 19 

 mean = sum / n 

TASK (Problem Solving)

Calculate mean of array  from scratch

1- create array with these values and

2- get length of array

3- get sum of array

4- get mean
 

In [74]:
x = np.array([2,3,6,1,2,5])
x

array([2, 3, 6, 1, 2, 5])

In [75]:
length = len(x)
length

6

In [76]:
summ = np.sum(x)
summ

19

In [77]:
mean = summ / length
mean

3.1666666666666665

In [78]:
np.mean(x)

3.1666666666666665

In [79]:
x=np.arange(1,7).reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
np.mean(x,axis=0)

array([2.5, 3.5, 4.5])

In [81]:
np.median(x,axis=0)

array([2.5, 3.5, 4.5])

In [83]:
# np.mode(x,axis=0)

In [ ]:
x = np.arange(0,20).reshape((4,5))
x

In [ ]:
mean_total = np.mean(x)
mean_total

In [ ]:
mean_columns = np.mean(x,axis=0)
mean_columns

## Bonus 

3- create this another array

[[ 1. 2. nan]

[ 4. nan 6.]

[nan 8 9]]

4- replace nan values by mean of array 

In [86]:
y = np.array([[1 ,2 ,np.nan],
              [4 ,np.nan ,6],
              [np.nan , 8 ,9]])
y

array([[ 1.,  2., nan],
       [ 4., nan,  6.],
       [nan,  8.,  9.]])

In [105]:
mean_total = np.nanmean(y,axis=0)

In [113]:
mean_total

array([2.5, 5. , 7.5])

way 1   Masking Boolean indexing

In [114]:
y = np.array([[1 ,2 ,np.nan],
              [4 ,np.nan ,6],
              [np.nan , 8 ,9]])
y

array([[ 1.,  2., nan],
       [ 4., nan,  6.],
       [nan,  8.,  9.]])

In [109]:
np.isnan(y)

array([[False, False,  True],
       [False,  True, False],
       [ True, False, False]])

In [115]:
y[np.isnan(y)]

array([nan, nan, nan])

In [118]:
mean_total

array([2.5, 5. , 7.5])

In [116]:
y[np.isnan(y)] = mean_total

In [117]:
y

array([[1. , 2. , 2.5],
       [4. , 5. , 6. ],
       [7.5, 8. , 9. ]])

another way  string

In [122]:
y = np.array([[1 ,2 ,np.nan],
              [4 ,np.nan ,6],
              [np.nan , 8 ,9]])
y

array([[ 1.,  2., nan],
       [ 4., nan,  6.],
       [nan,  8.,  9.]])

In [123]:
mean_total = np.nanmean(y,axis=0)

In [124]:
y = y.astype(str)

In [125]:
y

array([['1.0', '2.0', 'nan'],
       ['4.0', 'nan', '6.0'],
       ['nan', '8.0', '9.0']], dtype='<U32')

In [126]:
y[y == 'nan'] #masking

array(['nan', 'nan', 'nan'], dtype='<U32')

In [127]:
y[y=='nan'] = mean_total

In [128]:
y

array([['1.0', '2.0', '2.5'],
       ['4.0', '5.0', '6.0'],
       ['7.5', '8.0', '9.0']], dtype='<U32')

In [129]:
y = y.astype(float)

In [130]:
y

array([[1. , 2. , 2.5],
       [4. , 5. , 6. ],
       [7.5, 8. , 9. ]])

## np.Where

In [131]:
y = np.array([[1 ,2 ,np.nan],
              [4 ,np.nan ,6],
              [np.nan , 8 ,9]])
y

array([[ 1.,  2., nan],
       [ 4., nan,  6.],
       [nan,  8.,  9.]])

In [132]:
np.isnan(y)

array([[False, False,  True],
       [False,  True, False],
       [ True, False, False]])

In [133]:
y = np.where( np.isnan(y), #condition
             mean_total, #If True
             y # If False
             )
y

array([[1. , 2. , 7.5],
       [4. , 5. , 6. ],
       [2.5, 8. , 9. ]])

## Reference & Credits:

The tutorial above is a combination of the code/instructions created by 

Eng / Mahmoud Khorshed 